const data = [
  {
    id: 1,
    author: "welcome@it-knights.club",
    title: "Welcome in this lesson",
    emailText: "Long text may appear in this section",
    createdAt: "2021-08-14",
  },
  {
    id: 2,
    author: "mentor@it-knights.club",
    title: "Again new data",
    emailText: "Long text may appear in this section2",
    createdAt: "2015-08-15",
  },
  {
    id: 3,
    author: "mentor@it-knights.club",
    title: "Tests",
    emailText: "Test",
    createdAt: "2020-04-22",
  },
  {
    id: 4,
    author: "check@ukr.net",
    title: "hello from",
    emailText: "world's finest",
    createdAt: "2018-03-15",
  },
  {
    id: 5,
    author: "dealwitjs@gmail.com",
    title: "Deal",
    emailText: "JavaScript is cool",
    createdAt: "2015-08-15",
  },
  {
    id: 6,
    author: "superdev@yahoo.com",
    title: "I'm da best",
    emailText: "SUPPADUPA",
    createdAt: "2022-01-01",
  },
  {
    id: 7,
    author: "qwerty@deal.com",
    title: "SPAM",
    emailText: "Take this spam for free",
    createdAt: "2017-08-09",
  },
  {
    id: 8,
    author: "mentor@it-knights.club",
    title: "How are you?",
    emailText: "",
    createdAt: "2022-03-03",
  },
  {
    id: 9,
    author: "learn@js.com",
    title: "this",
    emailText: "is for you",
    createdAt: "2019-09-09",
  },
  {
    id: 10,
    author: "mentor@it-knights.club",
    title: "Solve these katas",
    emailText: "ASAP",
    createdAt: "2022-04-04",
  },
  {
    id: 11,
    author: "mentor@it-knights.club",
    title: "get out",
    emailText: "",
    createdAt: "2022-04-05",
  },
  {
    id: 12,
    author: "hello@google.com",
    title: "hello",
    emailText: "",
    createdAt: "2022-04-05",
  },
];
